[tool.poetry]
name = "faltu_space2"
version = "0.0.1"
description = "Birthday gift web app"
authors = ["samir <smartsamir0205@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
